### ISSUE TITLE
Shouldn't require a note unless the PR is an `add:` or `fix:`

### ISSUE THREAD

**Issue by ckerr** [electron/clerk#5]
Most PRs with other semantic commits are procedural items that don't matter.

It will be tedious to add a `notes: no-notes` for every `chore:`, `style:`, `refactor:`, `test:` etc..

**Comment by MarshallOfSound** [comment]
> Shouldn't require a note unless the PR is an `add:` or `fix:`

This isn't 100% true, `refactor:` and `ci:` PR's can actually fix issues.  E.g. the fix for the fetch POST issue was actually a `ci: ` change but we still want some nice release notes.  We want to separate the concept of release notes from the semantic commits.

> It will be tedious to add a notes: no-notes for every chore:, style:, refactor:, test: etc..

The work there would be minimal, I'd rather people have to take 10 seconds out of their day to add `notes: no-notes` at the bottom of the PR than we miss notes from a PR that really should have them.

**Comment by MarshallOfSound** [comment]
Solved in #4
