### ISSUE TITLE
new icon

### ISSUE THREAD

**Issue by zeke** [electron/clerk#8]
Hey I started working on a new icon. What do you think?

![clerk-icon](https://user-images.githubusercontent.com/2289/44223471-92ee4a80-a13c-11e8-8b53-6eff7e6acd95.png)

**Comment by zeke** [comment]
@MarshallOfSound what do you think? If you like, please give me access to the GitHub app so I can make changes.

**Comment by MarshallOfSound** [comment]
@zeke sorry had a quick offline discussion about this, love the icon but in order for me to give you access to it I need to lose access to it lol 😆 We need to figure out a long term place to put all our bots / apps so that I can update them.  At the moment only org owners can view / edit app configuration.

**Comment by zeke** [comment]
> At the moment only org owners can view / edit app configuration.

Ah so you'd lose access if we moved it to the @electron org? I see Trop lives there. Have you been encumbered by not being a Trop admin?

In the meantime, can you update the icon on my behalf?
